config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get :mypage, to: "mypage#index"

  resources :taggings
  resources :books
  resources :tags, except: :show
  resources :products, only: [:index, :show] 
  
  
  resources :orders, only: [:new, :create] do
    collection do
      get :confirm
      get :complete
    end
  end
  
  resources :line_items, only: [:create, :destroy]
  resources :carts, only: [:show, :destroy]
  resources :quentity

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy 
  has_many :books, through: :order_details

  def total_price
    order_details.sum { |order| order.total_price}
  end

  def total_number
    order_details.sum { |order| order.total_quantity}
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
     @order = Order.new
     @books = @current_cart.books

     sold_out_books = @current_cart.books.where(status: :sold_out)
    if sold_out_books.exists?
      redirect_to products_path
      return
    end
  end
    
  def confirm
    @count = order_params[:count]
    @order = Order.new(order_params)
    # @book = Book.find(@order.book_id) #new アクションで設定された @book 変数
    @books = Book.where(id: order_params[:book_ids]) #new アクションで設定された @book 変数
    @line_items = @current_cart.line_items

    order_params[:count].each_with_index do |count, index|
    book_id = order_params[:book_ids][index]
    line_item = @line_items.find_by(book_id: book_id)
  
      if line_item.present?
        line_item.update(quantity: count)
      end
    end
  end

  #   @books.each do |book|
  #     if book.sold_out?
  #       redirect_to product_path(book)
  #       flash[:alert] = "This item is currently sold out and unavailable for purchase...🙇"
  #     return
  #     end
  #   end
  # end

  def create
    count = order_params[:count].map(&:to_i).sum
    @order = Order.new(address: order_params[:address], count: count)
    @books = Book.where(id: order_params[:book_ids])
    @line_items = @current_cart.line_items

    if @order.save
      OrderDetail.create_items(@order, @line_items)
      
      @line_items.each do |item|
        item.book.sold_out!
      end
        redirect_to complete_orders_path(@order), notice: "Order was successfully placed!"
    else
      render "confirm"
    end
  end


  def complete
    @orders = Order.where(id: params[:id])
    CompleteMailer.complete_mail(current_user).deliver
  end

  # order/new...book_id=1 で飛ぶときに　@bookをリンクに入れることで詳細画面に戻り、自然にページを移るようにできた
  private

  def order_params
    params.require(:order).permit(:status, :address, count: [], book_ids: [])
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/complete.html.erb
<div style="background-color: #B3E5FC; padding: 20px; border-radius: 10px; text-align: center;">
  <p style="font-size: 24px; color: #333; font-family: 'Helvetica Neue', Arial, sans-serif; font-weight: bold;">
    +.*☁️ Thank you!☺ Your order has been completed.🐈🐾+.*</p>

  <%= link_to "🔙Back to books", products_path %>
</div>

 

app/views/orders/confirm.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Confirmation</title>

<style>
.coment {
  display: flex;
  justify-content: center; 
  align-items: center;
}
.link {
  background-color: #B2EBF2; /* パステルの黄色 (#FFF176) */
  padding: 10px 20px; /* パディングを適切に設定 */
  text-decoration: none; /* 下線を削除 */
  color: black; 
  border-radius: 5px; 
  border: none;
  font-size: 15px;
}

.link:hover {
  background-color:  #80DEEA;
  /* ホバー時の色変更 */
}
</style>

</head>
<div class="centered-box">
<h1>☑Confirmation</h1>
<h3 class="coment">🐱<[Please, confirm your order.]</h3>

  <div class="center">
  <%= form_with(model: @order, local: true) do |form| %>
    <% if @order.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@order.errors.count, "error") %> prohibited this article from being saved:</h2>

          <ul>
            <% @order.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <% @books.each do |book|%>
      <div class="field">
      <%= form.hidden_field :book_ids, value: book.id, name: "order[book_ids][]" %>
      </div>
    <% end %>

    <div class="field">
    <%= form.hidden_field :count, value: @current_cart.total_number, name: "order[count][]" %>
    </div>


    <% @line_items.each do |line_item| %>
      <% book = line_item.book %>
      <div>
        <p>📖 Title: <%= book.title %></p>
        <p>◆ Quantity: <%= line_item.quantity %>items</p>
        <p>
          💰 Price: ￥<%= line_item.item_total_price %>
          <span>(Including tax)</span>
        </p>
      </div>
    <% end %>

    <br>
    <strong>
    <div class="total-section">
        <p>📚 Quantity of orders: <%= @current_cart.total_number %><%= "item".pluralize(@current_cart.total_number) %></p>
        💴 Total price: ￥<%= @current_cart.total_price %>(Including tax)
    </div>
    </strong>

    <br>
    <div class="field" style="display: inline-block;">
      <%= form.label :address %>
      <%= @order.address %>
      <%= form.hidden_field :address %>
    </div>
        
    <div class="actions">
      <%= form.submit "Confirm your order.",class:"link" %>
    </div>
  <% end %>
</div>
</div>
</body>
</html>

app/views/orders/index.html.erb
<h1>All Orders</h1>

<% @orders.each do |order| %>
  <div>
  <p><strong>Count</strong> <%= order.count %></p>
  <p><strong>Address:</strong> <%= order.address %></p>
  <p><strong>Book ID:</strong> <%= order.id %></p>
  </div>
<% end %>

app/views/orders/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Order🐧</title>

<style>
.link {
  background-color: #FFF176; /* パステルの黄色 (#FFF176) */
  padding: 10px 20px; /* パディングを適切に設定 */
  text-decoration: none; /* 下線を削除 */
  color: black; 
  border-radius: 5px; 
  border: none;
  font-size: 16px;
}

.link:hover {
  background-color: #FFEB3B; 
  /* ホバー時の色変更 */
}

.under {
  font-size: 15px;
}
</style>
</head>

<body>
<div class="centered-box">
  <h1>Order🐧</h1>

  <%= form_with(model: @order, local: true, url: confirm_orders_path, method: :get) do |form| %>
    <% if @order.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>
        <ul>
          <% @order.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <% @books.each do |book| %>
      <strong>📖Title:<%= book.title %></strong>

      <div class="field">
        <%= form.label :count %>
        <%= form.text_field :count, name: "order[count][]", value: LineItem.find_by(cart_id: @current_cart, book_id: book).quantity %>
      </div>

      <div class="field">
        <%= form.hidden_field :book_ids, value: book.id, name: "order[book_ids][]" %>
      </div>
      
    <% end %>

    <br>

    <div class="field">
      <%= form.label :address %>
      <%= form.text_field :address %>
    </div>

    <br>
      <div class="actions">
        <%= form.submit "Proceed to the next step.", class: "link" %>
      </div>

  <% end %>

  <br>
  <div class="under">
  <%= link_to "Back to shopping cart", cart_path(session[:cart_id])%>
  </div>
</div>

</body>
</html>
