config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get :mypage, to: "mypage#index"

  resources :taggings
  resources :books
  resources :tags, except: :show
  resources :products, only: [:index, :show] 
  
  
  resources :orders, only: [:new, :create] do
    collection do
      get :confirm
      get :complete
    end
  end
  
  resources :line_items, only: [:create, :destroy]
  resources :carts, only: [:show, :destroy]
  resources :quentity

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings

    enum status: {on_sale: 1, sold_out: 2}

    has_many :line_items, dependent: :destroy

    has_many :order_details, dependent: :destroy 
    has_many :orders, through: :order_details

    has_one_attached :photo
    def thumbnail
        photo.variant(resize_to_fill: [300, 300])
      end
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :books, through: :line_items

  def add_product(book_id)
    line_items.find_or_initialize_by(book_id: book_id)
  end

  def total_price
    line_items.to_a.sum {|item| item.item_total_price}
  end

  def total_number
    line_items.to_a.sum {|item| item.quantity}
  end
end

# through: :line_items は、中間テーブルとして LineItem を使用して Cart と Book を関連付けています。
# これにより、Cart インスタンスは、そのカート内のすべての Book レコードにアクセスできます。
# 具体的には、cart.books を使用して、特定のカートに関連付けられたすべての Book レコードを取得できます。

# ある本（Book）がカートに追加された回数を取得
# cart.books.find_by(title: 'Ruby Book').line_items.count

app/models/complete.rb
class Complete < ApplicationRecord
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart
  belongs_to :book

  def add_product(book_id)
    line_items.find_or_initialize_by(book_id: book_id)
  end

  def item_total_price
    book.price * quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy 
  has_many :books, through: :order_details

  def total_price
    order_details.sum { |order| order.total_price}
  end

  def total_number
    order_details.sum { |order| order.total_quantity}
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :book
  belongs_to :order

  def self.create_items(order,line_items)
    line_items.each do |item|
    OrderDetail.create!(order_id: order.id, book_id: item.book_id, quantity: item.quantity)
    LineItem.find(item.id).delete
    end
  end

  def total_price
    book.price * quantity
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings
    has_many :books, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :book
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :trackable, :rememberable, :validatable
end

# :recoverable

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy!

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:title, :author, :publushed_on, :showing, :price, :status, :photo, tag_ids: [])
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
before_action :current_cart

  def show
    @line_items = @current_cart.line_items
  end
  
  def add_product(book_id)
    line_items.find_or_initialize_by(book_id: book_id)
  end

  def destroy
    session[:cart_id] = nil
    redirect_to products_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @books = Book.all
  end
 # GET /books/1 or /books/1.json
  def show
    @book = Book.find(params[:id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[ edit update destroy ]#show->edit only

  # GET /tags or /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1 or /tags/1.json
  # def show
  # end 0604

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tags_url, notice: "Tag was successfully created." }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tags_url, notice: "Tag was successfully updated." }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.destroy!

    respond_to do |format|
      format.html { redirect_to tags_url, notice: "Tag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def current_cart?(book, cart)
    cart.line_items.map{|i| i.book_id}.include?(book.id)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/products/index.html.erb

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Books</title>

  <style>
  .center-section {
    font-size: 30px;
    }
  
  .resized-image {
    width: 150px; /* 幅を150pxにリサイズ */
    height: auto; /* 高さを自動調整 */
    display: block; /* インライン要素からブロック要素に変更 */
    margin: 0 auto; /* 左右のマージンを自動設定して中央揃え */
    border: 3px solid #ccc;
  }
  </style>
</head>

<body>
  <header>
    <div class="header-content">
      <div class="left-section">
        <div class="welcome-message">
          <% if current_user %>
            Welcome! <%= current_user.email %> 
          <% else %>
          <% end %>
        </div>
        <div class="my-page-link">
          <%= link_to "👤 Mypage", session_path(current_user) %>
        </div>
      </div>
        
      <div class="center-section">
        Books📚
      </div>

      <div class="right-section">
          <% if session[:cart_id] %>
            <div class="add">
              <%= link_to "Check shopping cart", cart_path(session[:cart_id])%>
            </div>
          <% end %>
      </div>
    </div>
  </header>
      
  <div class="notification">
    <%= notice %>
  </div>


  <div class="container">
    <table>
    <thead>
        <tr>
          <th>📸Image</th>
          <th>.*★📖Title*.⁺:</th>
          <th>👤Author</th>
          <th>⌚Publushed on</th>
          <th>📚Status</th>
          <th>💴Price</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <% if book.photo.attached? %>
                <%= image_tag book.thumbnail, class:"resized-image" %>
              <% end %>
            </td>
            <td class="title-header"><%= link_to book.title, product_path(book) %></td>
            <td><%= book.author %></td>
            <td><%= book.publushed_on %></td>
            <td>
              <% if book.on_sale? %>
                <span style="color: green;">On sale</span>
              <% elsif book.sold_out? %>
                <span style="color: red;">Sold out</span>
              <% end %>
            </td>
            <td><%= book.price %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</body>
</html>

app/views/products/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <style>
  .book-info p {
    margin: 5px 0; 
  }
  
  .add {
    background-color: #FFC896; /* パステルの黄色 (#FFF176) */
    padding: 10px 20px; /* パディングを適切に設定 */
    text-decoration: none; /* 下線を削除 */
    color: black; 
    border-radius: 5px; 
    # display: inline-block;
    # cursor: pointer;
  }
  
  .add:hover {
    background-color: #FFB680; 
  }
  </style>
  </head>
  
<body>
  <header>
    <div class="header-content">
      <div class="center-section">
      Book details
      </div>
    </div>
  </header>
    
  <table class="table">
    <div class="center">
    <thead>
      <tr>
      <th><strong>📸Image</strong></th>
      <th><strong>.*★📖Title*.⁺:</strong></th>
      <th><strong>👤Author:</strong></th>
      <th><strong>⌚Publushed on</strong></th>
      <th><strong>📚Status:</strong>
      <th><strong>💴Price:</strong></th>
    </thead>

    <tbody>
      <tr>
      <td><% if @book.photo.attached? %>
          <%= image_tag @book.thumbnail %>
          <% end %>
      </td>
      <td><%= @book.title %></td>
      <td><%= @book.author %></td>
      <td><%= @book.publushed_on %></td>
      <td>
      <% if @book.on_sale? %>
        <span style="color: green;">On sale</span>
      <% elsif @book.sold_out? %>
        <span style="color: red;">Sold out</span>
      <% end %>
      </td>
      <td><%= @book.price %></td>
    </tbody>
    </div>
  </table>

  <div class="center">
    <% if @book.on_sale? %>
      <%= link_to "Add to cart🛒=3", line_items_path(book_id: @book.id),
      data: {"turbo-method": :post}, class: "add" %>
    <% else %>
      <% flash.now[:alert] = "This item is currently sold out and unavailable for purchase...🙇" %>
    <% end %>
  </div>

  <div class="left-section">
  <%= link_to "🔙Back to books", products_path %>
  </div>
</body>
</html>

<!-- <%= link_to "Order", new_order_path(book_id: @book.id), class:"order" %> -->